# This is a text editor! Type in here!
[server]
esp32_serial = "usb-1a86_USB_Single_Serial_585D015807-if00"

[server.video_device]
friendly_name = "WARRKY USB 3.0"
resolution = "1920x1080"
fps = "60.000"

[client]
hostname = "10.20.30.90"
hwinfo_port = "60000" # Unless you've changed it!
ssh_username = "rawhide"
# MAKE SURE YOU USE SINGLE QUOTES, THIS HAS TO BE A LITERAL
# Alternatively, just make sure ycruncher and ryzen-smu-cli are in your PATH and leave it as it is
ryzen_smu_cli_path = 'C:\Users\rawhide\Downloads\ryzen-smu-cli-0.0.2\ryzen-smu-cli.exe'
ycruncher_path = 'C:\Users\rawhide\Downloads\y-cruncher v0.8.6.9545\y-cruncher v0.8.6.9545\y-cruncher.exe'
bios_map_path = 'bios-maps/asus/x870-gaming-plus-wifi.gv'

[client.overclocking.common] # Just some ideas of how the settings may work for your system
"ACPI SRAT L3 Cache As NUMA Domain" = "Enabled"
"PBO Limits" = "Motherboard"
"Precision Boost Overdrive Scalar" = "10X"
"Max CPU Boost Clock Override(+)" = "200"
"Integrated Graphics" = "Disabled"
"Voltage training" = "Enabled"
"CPU Load-line Calibration" = "Level 8"
"CPU Current Capability" = "140%"
"Fixed CPU VRM Switching Frequency(KHz)" = "700"
"CPU Power Phase Control" = "Extreme"
"VDDSOC Current Capability" = "140%"
"Fixed VDDSOC Switching Frequency(KHz)" = "700"
"VDDSOC Power Phase Control" = "Extreme"

[client.overclocking.cpu]

[client.overclocking.memory]
# "DRAM Profile Setting" = "XMP1-6000"
# "DRAM Performance Mode" = "Aggressive"
"VDDSOC Voltage Override" = "1.2"